version: "3"
services:
  wordstats-service:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      MONGO_URI: mongodb://mongo/?replSet=rs0
    ports:
      - "5000:5000"
    volumes:
      - ./src:/usr/src/app/src
      - ./specs:/usr/src/app/specs
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - ./build:/usr/src/app/build
      - ./assets:/usr/src/app/assets
    links:
      - mongo
      - redis
    depends_on:
      - mongo
      - redis
    restart: always
  redis:
    image: redis:5.0.7
    ports:
      - "6379:6379"
    logging:
      driver: none
  mongo:
    image: mongo:4.4.0
    command: mongod --bind_ip_all --replSet rs0
    container_name: mongo
    hostname: mongo
    restart: always
    ports:
      - "27017:27017"
    logging:
      driver: none
